version: '2'

services:

  camilo:
    restart: always
    image: ensi-secu/devoir2:latest
    ports:
      - 8080:80
    links:
      - camilo-mysql:mysql

  camilo-mysql:
    restart: always
    image: mysql:5.7
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=chamilo
      - MYSQL_USER=chamilo
      - MYSQL_PASSWORD=azertyuiop
    ports:
      - 3306:3306
